<a href="https://colab.research.google.com/github/chandini2595/Tensor-Operations/blob/main/Colab_Files/Tensor_Pytorch_Einum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

# Check PyTorch version
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.5.1+cu124


In [8]:
# Creating Tensors
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:", matrix)
print("Tensor:", tensor)


Scalar: tensor(7)
Vector: tensor([1, 2, 3])
Matrix: tensor([[1, 2],
        [3, 4]])
Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [9]:
# Tensor Operations
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print("Addition:\n", x + y)  # Element-wise addition
print("Multiplication:\n", x * y)  # Element-wise multiplication
print("Matrix Multiplication:\n", torch.matmul(x, y))  # Matrix multiplication


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [10]:
# Reshaping Tensors
reshaped_tensor = tensor.view(2, 4)  # Changing shape without altering data
print("Reshaped Tensor:\n", reshaped_tensor)


Reshaped Tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [11]:
# Advanced Tensor Operations
# Example 1: Transpose
t_transposed = torch.transpose(x, 0, 1)
print("Transposed Tensor:\n", t_transposed)

Transposed Tensor:
 tensor([[1., 3.],
        [2., 4.]])


In [12]:
# Example 2: Squeeze and Unsqueeze
t_squeezed = torch.squeeze(torch.tensor([[[1], [2], [3]]]))
print("Squeezed Tensor:\n", t_squeezed)

t_unsqueezed = torch.unsqueeze(torch.tensor([1, 2, 3]), dim=1)
print("Unsqueezed Tensor:\n", t_unsqueezed)


Squeezed Tensor:
 tensor([1, 2, 3])
Unsqueezed Tensor:
 tensor([[1],
        [2],
        [3]])


In [13]:
# Example 3: Permutation (Rearranging dimensions)
z = torch.rand(2, 3, 4)
z_permuted = z.permute(2, 0, 1)
print("Permuted Tensor Shape:\n", z_permuted.shape)



Permuted Tensor Shape:
 torch.Size([4, 2, 3])


In [14]:
# Example 4: Element-wise exponentiation
t_exp = torch.pow(x, 2)
print("Element-wise exponentiation:\n", t_exp)



Element-wise exponentiation:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


In [15]:

# Example 5: Einsum-style operations with PyTorch
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
einsum_result1 = torch.einsum('ij,ij->ij', [a, b])  # Element-wise multiplication
print("Einsum - Element-wise multiplication:\n", einsum_result1)


Einsum - Element-wise multiplication:
 tensor([[ 5, 12],
        [21, 32]])


In [16]:

einsum_result2 = torch.einsum('ik,kj->ij', [x, y])  # Matrix multiplication
print("Einsum - Matrix Multiplication:\n", einsum_result2)

einsum_result3 = torch.einsum('ij->i', torch.tensor([[1, 2, 3], [4, 5, 6]]))  # Column-wise sum
print("Einsum - Sum across columns:\n", einsum_result3)



Einsum - Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])
Einsum - Sum across columns:
 tensor([ 6, 15])


In [17]:
# Example 6: Using Einops for tensor manipulations
from einops import rearrange, reduce

# Rearranging (similar to permute but more intuitive)
z_rearranged = rearrange(z, 'b c h -> h b c')
print("Einops - Rearranged Tensor Shape:\n", z_rearranged.shape)

# Reducing (e.g., summing over dimensions)
z_reduced = reduce(z, 'b c h -> b h', 'sum')
print("Einops - Reduced Tensor Shape:\n", z_reduced.shape)

Einops - Rearranged Tensor Shape:
 torch.Size([4, 2, 3])
Einops - Reduced Tensor Shape:
 torch.Size([2, 4])
